<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>

    <RootNamespace>ThpsQScriptEd</RootNamespace>
    <AssemblyName>ThpsQScriptEd</AssemblyName>
    <StartupObject>ThpsQScriptEd.Program</StartupObject>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="data\exefuncs.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\exefuncs_th4.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\exefuncs_ug1.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\scriptfuncs_th3.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\qScript_def.xml" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\qScriptSyntexHighlighter.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
